name: Echo Pull Request Number

on:
  push:
    branches:
      - pr-test-2
    
jobs:
  echo-pr-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: all
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.number }}

          
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Install packages
    #     run: npm install
        
    #   - name: Branch name
    #     run: echo running on branch github ref is ${{github.ref}} github ref name is ${{github.ref_name}}

    #   - name: Show PR number
    #     env: 
    #       NUMBER: ${{ github.event.pull_request.number }}
    #     run: npm run package $NUMBER
        
    #   - name: JWalton Method
    #     uses: jwalton/gh-find-current-pr@master
    #     id: findPr
    #     with:
    #       state: all
    #     run: echo "Your PR is ${PR}"
    #     if: success() && steps.findPr.outputs.number
    #     env:
    #       PR: ${{ steps.findPr.outputs.pr }}
          
