name: Echo Pull Request Number

on:
  pull_request:
    branches:
      - main
      - develop
    
jobs:
  echo-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install
        
      - name: Branch name
        run: echo running on branch github ref is ${{github.ref}} github ref name is ${{github.ref_name}}

      - name: Show PR number
        env: 
          NUMBER: ${{ github.event.pull_request.number }}
        run: npm run package $NUMBER
