name: Echo Pull Request Number

on:
  push:
    branches: [ main ]
    
jobs:
  echo-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install
        
      - name: Branch name
        run: echo running on branch github ref ${{github.ref}} github head ref ${{github.head.ref}}

      - name: Show PR number
        env: 
          NUMBER: ${{ github.event.pull_request.number }}
        run: npm run package $NUMBER
