name: Echo Pull Request Number

on:
  push:
    branches:
      - pr-test-2
    
jobs:
  echo-pr-number:
    runs-on: EntRunner_Grp_Dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Find PR From Push Action
        uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
          
      - name: Echo PR Number
        run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Test1
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD HH_mm_ss_SSS"
      # Use the output from the `t1` step
      - name: Output1
        run: |
            echo "The time was ${{ steps.t1.outputs.time }}"
